# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

export JAVA_HOME={{ ac_java_home }}
export PATH=$JAVA_HOME/bin:$PATH

export ZOOKEEPER_HOME={{ zk_home }}
export HADOOP_HOME={{ ha_home }}
export ACCUMULO_HOME={{ ac_home }}

# Add the core Hadoop JARs
#
export CLASSPATH=
for file in $HADOOP_HOME/share/hadoop/{common/lib/*,*/*}.jar; do
    export CLASSPATH=$file:$CLASSPATH
done

for file in $ACCUMULO_HOME/lib/*.jar; do
    export CLASSPATH=$file:$CLASSPATH
done

# Create the alias
#
alias cda='cd $ACCUMULO_HOME; pwd'
