- name: EC2 Instance
  hosts: servers
  connection: local
  tasks:
  - name: Initialize with the SSH Rule
    set_fact:
      tcp_rules: "{{ [{'proto': 'tcp', 'cidr_ip': '0.0.0.0/0', 'from_port': '22', 'to_port': '22' }] }}"

  - name: Prepare the Rules for the 'ZK-HA-AC-Restricted' Security Group
    set_fact:
      tcp_rules: "{{ tcp_rules + [{'proto': 'tcp', 'cidr_ip': item[0] + '/32', 'from_port': item[1], 'to_port': item[1]}] }}"
    with_nested:
      - "{{ hosts }}"
      - "{{ ports }}"

  - name: EC2 Security Group
    ec2_group:
      name: "{{ security_group }}"
      description: Zookeeper, Hadoop, Accumulo Cluster Security Group
      vpc_id: "{{ vpc_id }}"
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      rules: "{{ tcp_rules }}"
