- name: Zookeeper
  hosts: servers
  become: true
  become_user: "{{ zk_user }}"
  tasks:
    - name: Ensure config file contains the correct data directory reference
      lineinfile:
        path: "{{ zk_home }}/conf/{{ zk_conf }}"
        regexp: "^dataDir=.*"
        line: "dataDir={{ zk_data_dir }}"

    - name: Ensure config file contains the correct client port
      lineinfile:
        path: "{{ zk_home }}/conf/{{ zk_conf }}"
        regexp: "^clientPort=.*"
        line: "clientPort={{ zk_client_port }}"

    - name: Ensure config file contains the correct servers on each host
      lineinfile:
        path: "{{ zk_home }}/conf/{{ zk_conf }}"
        regexp: "^server.{{ index+1 }}=.*"
        line: "server.{{ index+1 }}={{ item }}:{{ zk_peer_port }}:{{ zk_leader_port }}"
      loop: "{{ ansible_play_hosts }}"
      loop_control:
        index_var: index

    - name: Restart the Zookeeper daemon
      shell:
        cmd: "./bin/zkServer.sh restart {{ zk_home }}/conf/{{ zk_conf }}"
        chdir: "{{ zk_home }}"

    - name: Check that the daemon status shows that it is running in a cluster
      shell:
        cmd: "./bin/zkServer.sh status"
        chdir: "{{ zk_home }}"
      register: command_result
      failed_when: "'Mode: follower' not in command_result.stdout and 'Mode: leader' not in command_result.stdout"

