- name: Zookeeper Configuration
  hosts: servers
  become: true
  become_user: "{{ zk_user }}"
  tasks:
    - name: Template for 'zoo.cfg'
      template:
        src: ../templates/zookeeper/zoo.cfg
        dest: "{{ zk_home }}/conf/{{ zk_conf }}"
        owner: "{{ zk_user }}"
        group: "{{ zk_group }}"
        mode: '0644'

    - name: Template for 'myid'
      template:
        src: ../templates/zookeeper/myid
        dest: "{{ zk_data_dir }}/myid"
        owner: "{{ zk_user }}"
        group: "{{ zk_group }}"
        mode: '0644'
      vars:
        server_count: "{{ groups['servers'].index(inventory_hostname) + 1 }}"

    - name: Template for 'bashrc'
      template:
        src: ../templates/zookeeper/bashrc
        dest: "{{ zk_bashrc }}"
        owner: "{{ zk_user }}"
        group: "{{ zk_group }}"
        mode: '0644'
